# SOVD2UDS Adapter Configuration

[server]
# HTTP server configuration
host = "127.0.0.1"
port = 8081
# Request timeout in seconds
request_timeout = 30

[uds]
# UDS communication settings
interface = "can0"
# Default ECU address (can be overridden per component)
default_address = 0x7E0
# UDS request timeout in milliseconds
timeout = 5000
# Maximum retry attempts
max_retries = 3

[doip]
# Diagnostics over IP settings
enabled = true
target_address = "192.168.1.100"
port = 13400
# Logical address
source_address = 0x0E80
target_logical_address = 0x1000

[logging]
# Logging configuration
level = "info"
# Format: "json" or "pretty"
format = "pretty"
# Log to file
log_file = "sovd2uds-adapter.log"
# Enable request/response logging
log_requests = true

[components]
# Component to ECU address mapping
# Format: component_id = ecu_address
engine = 0x7E0
transmission = 0x7E1
abs = 0x7E2
airbag = 0x7E3

[security]
# Security access configuration
# Enable security access for write operations
require_security_access = false
# Security access level
security_level = 0x01

[performance]
# Performance tuning
# Maximum concurrent requests
max_concurrent_requests = 10
# Connection pool size
connection_pool_size = 5
